### PR TITLE
Adding anaconda-project and related files

### PR DESCRIPTION
**Pull request by jsignell**
See https://nyc-taxi.pyviz.demo.anaconda.com  and https://nyc-taxi-notebook.pyviz.demo.anaconda.com

### CODE REVIEW

**Comment by jbednar** [comment]
image

**Comment by jsignell** [comment]
I commented before they'd finished deploying. They are there now.

**Comment by jbednar** [comment]
Ok, thanks. Is the notebook meant to be uncleared?

**Comment by jsignell** [comment]
> Ok, thanks. Is the notebook meant to be uncleared?

Hmm. Probably not. @philippjfr?

**Comment by philippjfr** [comment]
No, probably my mistake.

**Comment by jsignell** [comment]
Ok I'll check it in empty

**Comment by jbednar** [comment]
No, I mean that it's cleared, which means that it's empty when deployed.  I normally wouldn't want to deploy a runnable notebook, but when I do, I think I'd want it to run automatically so that I don't pointlessly ask the user to step through the cells (given that they can't edit them).  Anyway, there may not be anything we can do about this, as having the uncleared notebook may be even more confusing, as it will look live but won't be until the cells are re-run.

**Comment by jsignell** [comment]
Ah right this goes back to https://github.com/pyviz-topics/examples/issues/5. AFAIK there is no good way to force AE to execute on deploy. I think we'd need to create a new notebook argument. I agree that checking in an uncleared version is even more confusing.

**Pull request merged**
